
# Visualization Exercise

In this notebook, you will visualize various aspects of our solar system using matplotlib and seaborn. 
You'll explore different types of plots, analyze relationships between attributes, and derive insights based on the data.

## Dataset:
The dataset includes fictional data on the planets and moons of our solar system, including attributes like:
- `Planet`: Name of the planet
- `Distance_from_Sun`: Average distance of the planet from the Sun (in million km)
- `Mass`: Mass of the planet (in 10^24 kg)
- `Radius`: Radius of the planet (in km)
- `Number_of_Moons`: Number of moons orbiting the planet
- `Orbital_Period`: Length of the planet's year (in Earth days)
- `Rotation_Period`: Time taken for the planet to complete one rotation (in Earth hours)
- `Temperature`: Average surface temperature (in Celsius)

Every section contains a plot to be made and questions to think about. You do not have to answer the questions, they are simply here to make you think what is theoretically possible to derive from data.

In [1]:
import pandas as pd

# Solar system data (fictional values for demonstration)
data = {
    'Planet': ['Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune'],
    'Distance_from_Sun': [57.9, 108.2, 149.6, 227.9, 778.3, 1427.0, 2871.0, 4497.1], 
    'Mass': [0.33, 4.87, 5.97, 0.642, 1898, 568, 86.8, 102],  
    'Radius': [2439, 6051, 6371, 3389, 69911, 58232, 25362, 24622], 
    'Number_of_Moons': [0, 0, 1, 2, 79, 82, 27, 14],
    'Orbital_Period': [88, 225, 365, 687, 4333, 10759, 30687, 60190], 
    'Rotation_Period': [1407.6, -5832.5, 23.9, 24.6, 9.9, 10.7, -17.2, 16.1], 
    'Temperature': [167, 464, 15, -65, -110, -140, -195, -200]
}

df = pd.DataFrame(data)
df

,Planet,Distance_from_Sun,Mass,Radius,Number_of_Moons,Orbital_Period,Rotation_Period,Temperature
0,Mercury,57.9,0.330,2439,0,88,1407.6,167
1,Venus,108.2,4.870,6051,0,225,-5832.5,464
2,Earth,149.6,5.970,6371,1,365,23.9,15
3,Mars,227.9,0.642,3389,2,687,24.6,-65
4,Jupiter,778.3,1898.000,69911,79,4333,9.9,-110
5,Saturn,1427.0,568.000,58232,82,10759,10.7,-140
6,Uranus,2871.0,86.800,25362,27,30687,-17.2,-195
7,Neptune,4497.1,102.000,24622,14,60190,16.1,-200


## Exercise 1: Bar Plot
Create a **bar plot** to compare the number of moons for each planet.

- X-axis: Planets
- Y-axis: Number of Moons

Questions to think about:
- Which planet has the most moons? 
- Can you spot a relationship between the number of moons and the planet's position in the solar system?


## Exercise 2: Scatter Plot
Create a **scatter plot** to show the relationship between the distance from the Sun and the orbital period of each planet.

- X-axis: Distance from Sun 
- Y-axis: Orbital Period

Questions to think about:
- What kind of relationship do you observe between these two variables? 
- Does the distance from the Sun have an impact on the length of a planet's year


## Exercise 3: Violin Plot
Create a **violin plot** to compare the temperature distributions of the planets.

- X-axis: Planets
- Y-axis: Temperature (Celsius)

Questions to think about:
- Which planet has the widest temperature range?
- How does the temperature distribution vary between planets close to the Sun and those farther away?


## Exercise 4: Heatmap
Create a **heatmap** showing the correlation between the different numeric attributes of the planets.

Questions to think about:
- Which attributes seem to be most strongly correlated?
- Can you identify any interesting patterns in the data?


## Exercise 5: Pie Chart
Create a **pie chart** to show the proportion of total mass of all planets contributed by each individual planet.

Questions to think about:
- Which planet has the largest share of the total mass in the solar system?
- How do the smaller planets compare to the gas giants in terms of mass?